name: Auto Run Every Hour

on:
  schedule:
    # - cron: '0 * * * *' # æ¯å°æ—¶
    - cron: '0 16 * * *'   # æ¯å¤© 0:00ï¼ˆä¸œå…«åŒºï¼‰
    - cron: '0 22 * * *'  # æ¯å¤© 6:00ï¼ˆä¸œå…«åŒºï¼‰
    - cron: '0 4 * * *'   # æ¯å¤© 12:00ï¼ˆä¸œå…«åŒºï¼‰
    - cron: '0 10 * * *'  # æ¯å¤© 18:00ï¼ˆä¸œå…«åŒºï¼‰
  workflow_dispatch:

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests tqdm

    - name: Run run_all.py
      run: python run_all.py

    - name: Push updates
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "ğŸ¤– è‡ªåŠ¨æ›´æ–°æ—¶é—´ä¸ºï¼š$(date '+%Y-%m-%d %H:%M:%S')" || echo "nothing to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
